name: Java CI with Maven
on:
push:

branches: [ &quot;master&quot; ]
jobs:
maven:
runs-on: ubuntu-latest
steps:
- name: Checkout Repository
uses: actions/checkout@v4
- name: Set up JDK 17
uses: actions/setup-java@v4
with:
java-version: &#39;17&#39;
distribution: &#39;temurin&#39;
- name: Build with Maven
run: mvn compile
- name: Run the App
run: java -cp target/classes com.example.HelloWorld
